# Generated by Django 3.1.4 on 2021-02-28 17:40

import ckeditor.fields
import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=core.models.post_image_file_path)),
                ('description', ckeditor.fields.RichTextField(max_length=180)),
                ('body', ckeditor.fields.RichTextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('technologies', models.ManyToManyField(to='core.Technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
