# Generated by Django 3.1.4 on 2021-02-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
    ]
