# Generated by Django 3.1.4 on 2021-02-05 05:24

import ckeditor.fields
from django.db import migrations, models
import mlarticles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=mlarticles.models.article_image_file_path)),
                ('description', ckeditor.fields.RichTextField(max_length=180)),
                ('slug', models.CharField(max_length=240, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('link', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
